
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER: INTERNAL://:9092, EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092, EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT, INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  init-kafka1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka1
    entrypoint: [ '/bin/bash', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka1:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka1:9092 --create --if-not-exists --topic raw_data_topic --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka1:9092 --create --if-not-exists --topic ml_results_topic --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka1:9092 --list
      "

  kafka2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka2
    ports:
      - "29093:29093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER: INTERNAL://:9093, EXTERNAL://:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9093, EXTERNAL://localhost:29093 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT, INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  init-kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka2
    entrypoint: [ '/bin/bash', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka2:9093 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka2:9093 --create --if-not-exists --topic processed_data_topic --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka2:9093 --list
      "
  